force-app/main/default/objects/Guild__c/Guild__c.object-meta.xml
<CustomObject>
    <label>Guild</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guilds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/Hero__c.object-meta.xml
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Heroes</relationshipLabel>
    <relationshipName>Heroes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mission_Assignment__c/Mission_Assignment__c.object-meta.xml
<CustomObject>
    <label>Mission Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mission Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Mission_Assignment__c/fields/Hero__c.field-meta.xml
<CustomField>
    <fullName>Hero__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hero</label>
    <referenceTo>Hero__c</referenceTo>
    <relationshipLabel>Mission Assignments</relationshipLabel>
    <relationshipName>Mission_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mission_Assignment__c/fields/Mission__c.field-meta.xml
<CustomField>
    <fullName>Mission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mission</label>
    <referenceTo>Superhero_Mission__c</referenceTo>
    <relationshipLabel>Mission Assignments</relationshipLabel>
    <relationshipName>Mission_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Superhero_Mission__c/Superhero_Mission__c.object-meta.xml
<CustomObject>
    <label>Superhero Mission</label>
    <nameField>
        <displayFormat>SHM-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Superhero Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Superhero_Mission__c/fields/Complexity_Rank__c.field-meta.xml
<CustomField>
    <fullName>Complexity_Rank__c</fullName>
    <label>Complexity Rank</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Superhero_Mission__c/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Guild</label>
    <referenceTo>Guild__c</referenceTo>
    <relationshipLabel>Superhero Missions</relationshipLabel>
    <relationshipName>Superhero_Missions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Superhero_Mission__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MissionDetailController.cls
public without sharing class MissionDetailController {

    @AuraEnabled
    public static String getHeroMissionAssignments(){
        try {
            Id userId = UserInfo.getUserId();

            User user = [
                SELECT
                    Id,
                    ContactId
                FROM User
                WHERE Id =: userId
                LIMIT 1
            ];

            Hero__c hero = [
                SELECT
                    Id,
                    Name,
                    Contact__c,
                    Guild__c,
                    Rank__c
                FROM Hero__c
                WHERE Contact__c =: user.ContactId
                LIMIT 1
            ];

            List<Mission_Assignment__c> missionAssignments = [
                SELECT
                    Id,
                    Hero__c,
                    Mission__c,
                    Mission__r.Complexity_Rank__c,
                    Mission__r.Status__c,
                    Mission__r.Is_Public__c,
                    Status__c
                FROM Mission_Assignment__c
                WHERE Hero__c =: hero.Id
            ];

            return JSON.serialize(new HeroWrapper(hero, missionAssignments));

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void createMissionAssignment(String heroId, String missionId){
        try {
            insert new Mission_Assignment__c(
                Hero__c = heroId,
                Mission__c = missionId
            );
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void completeMission(String missionAssignmentId){
        try {
            Mission_Assignment__c missionAssignment = [
                SELECT
                    Id,
                    Status__c,
                    Mission__c
                FROM Mission_Assignment__c
                WHERE Id =: missionAssignmentId
                LIMIT 1
            ];

            missionAssignment.Status__c = Constants.STATUS_COMPLETED;

            update missionAssignment;

            updateMissionStatusToCompleted(missionAssignment.Mission__c);
            updateOtherMAStatusesToFailed(missionAssignment.Id, missionAssignment.Mission__c);

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public static void updateMissionStatusToCompleted(Id missionId) {

        String emailTextBody = 'Mission completed: ';

        Superhero_Mission__c mission = [
            SELECT
                Id,
                CreatedById,
                CreatedBy.Email,
                Status__c,
                Subject__c
            FROM Superhero_Mission__c
            WHERE Id =: missionId
        ];

        if (mission.Status__c == Constants.STATUS_AVAILABLE) {
            mission.Status__c = Constants.STATUS_COMPLETED;
            emailTextBody += mission.Subject__c;
        }

        update mission;

        sendEmailToMissionOwner(mission.CreatedBy.Email, mission.CreatedById, emailTextBody);
    }

    public static void sendEmailToMissionOwner(String ownerEmail, String ownerId, String emailTextBody) {
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();

        email.setTargetObjectId(ownerId);
        email.setSaveAsActivity(false);
        email.setSubject('Mission completed!');
        email.setPlainTextBody(emailTextBody);
        email.setToAddresses(new List<String>{ownerEmail});

        Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{email});
    }

    public static void updateOtherMAStatusesToFailed(String maId, String missionId) {

        List<Mission_Assignment__c> missionAssignmentsToUpdate = new List<Mission_Assignment__c>();

        List<Mission_Assignment__c> mas = [
            SELECT
                Id,
                Mission__c,
                Status__c
            FROM Mission_Assignment__c
            WHERE Id !=: maId
                AND Mission__c =: missionId
        ];

        for (Mission_Assignment__c ma : mas) {
            if (ma.Status__c == Constants.STATUS_IN_PROGRESS) {
                ma.Status__c = Constants.STATUS_FAILED;
                missionAssignmentsToUpdate.add(ma);
            }
        }

        update missionAssignmentsToUpdate;
    }

    public class HeroWrapper {
        public String heroId    { get; set; }
        public String name      { get; set; }
        public String rank      { get; set; }
        public String contactId { get; set; }
        public String guildId   { get; set; }
        public List<Mission_Assignment__c> missionAssignments { get; set; }
        public Integer numberOfActiveMissions { get; set; }

        public HeroWrapper(Hero__c hero, List<Mission_Assignment__c> missionAssignments) {
            this.heroId = hero.Id;
            this.name = hero.Name;
            this.rank = hero.Rank__c;
            this.contactId = hero.Contact__c;
            this.guildId = hero.Guild__c;
            this.missionAssignments = missionAssignments;

            List<Mission_Assignment__c> activeMissionAssignments = new List<Mission_Assignment__c>();

            for(Mission_Assignment__c ma : missionAssignments) {
                if (ma.Status__c == Constants.STATUS_IN_PROGRESS) {
                    activeMissionAssignments.add(ma);
                }
            }
            this.numberOfActiveMissions = activeMissionAssignments.size();
        }
    }
}