force-app/main/default/objects/Guild__c/Guild__c.object-meta.xml
<CustomObject>
    <label>Guild</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guilds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/Hero__c.object-meta.xml
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Heroes</relationshipLabel>
    <relationshipName>Heroes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Superhero_Mission__c/Superhero_Mission__c.object-meta.xml
<CustomObject>
    <label>Superhero Mission</label>
    <nameField>
        <displayFormat>SHM-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Superhero Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Superhero_Mission__c/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Guild</label>
    <referenceTo>Guild__c</referenceTo>
    <relationshipLabel>Superhero Missions</relationshipLabel>
    <relationshipName>Superhero_Missions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EmailService.cls
public with sharing class EmailService {

    public static void sendEmailsToGuildHeroes(List<Superhero_Mission__c> newGuildMissions) {
        Set<Id> guildIds = new Set<Id>();
        String emailBody = 'New missions: ';
        List<String> missionSubjects = new List<String>();

        for (Superhero_Mission__c mission : newGuildMissions) {
            guildIds.add(mission.Guild__c);
            missionSubjects.add(mission.Subject__c);
        }

        emailBody = emailBody + String.join(missionSubjects, ', ');

        List<Hero__c> guildHeroes = [
            SELECT
                Id,
                Contact__r.Email
            FROM Hero__c
            WHERE Guild__c IN: guildIds
        ];

        Map<String,Id> emailToUserIdMap = getEmailToUserIdMap(guildHeroes);
        List<Messaging.SingleEmailMessage> emailMessages = new List<Messaging.SingleEmailMessage>();

        for (Hero__c hero : guildHeroes) {
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();

            if (emailToUserIdMap.get(hero.Contact__r.Email) != null) {
                email.setTargetObjectId(emailToUserIdMap.get(hero.Contact__r.Email));
                email.setSaveAsActivity(false);
            }
            email.setSubject('New Missions!');
            email.setPlainTextBody(emailBody);
            email.setToAddresses(new List<String>{hero.Contact__r.Email});

            emailMessages.add(email);
        }

        Messaging.sendEmail(emailMessages);
    }

    public static void sendEmailsToAllHeroes(List<Superhero_Mission__c> newPublicMissions) {
        String emailBody = 'New missions: ';
        List<String> missionSubjects = new List<String>();

        for (Superhero_Mission__c mission : newPublicMissions) {
            missionSubjects.add(mission.Subject__c);
        }

        emailBody = emailBody + String.join(missionSubjects, ', ');

        Database.executeBatch(new SendEmailsToAllHeroesBatch(emailBody), 1);
    }

    public static Map<String,Id> getEmailToUserIdMap(List<Hero__c> heroes) {
        Set<Id> contactIds = new Set<Id>();
        Map<String,Id> emailToUserIdMap = new Map<String,Id>();

        for (Hero__c hero : heroes) {
            contactIds.add(hero.Contact__c);
        }

        List<User> users = [
            SELECT
                Id,
                Email
            FROM User
            WHERE ContactId IN: contactIds
        ];

        for(User user : users) {
            emailToUserIdMap.put(user.Email, user.Id);
        }

        return emailToUserIdMap;
    }
}