force-app/main/default/objects/Guild__c/Guild__c.object-meta.xml
<CustomObject>
    <label>Guild</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guilds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Superhero_Mission__c/Superhero_Mission__c.object-meta.xml
<CustomObject>
    <label>Superhero Mission</label>
    <nameField>
        <displayFormat>SHM-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Superhero Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Superhero_Mission__c/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Guild</label>
    <referenceTo>Guild__c</referenceTo>
    <relationshipLabel>Superhero Missions</relationshipLabel>
    <relationshipName>Superhero_Missions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AllMissionsCmpControllerTest.cls
@isTest
private with sharing class AllMissionsCmpControllerTest {

    @TestSetup
    private static void makeData(){
        Account acc = TestDataFactory.createAccount();
        User user = TestDataFactory.createCommunityUser(acc.Id);
        List<Guild__c> guilds = TestDataFactory.createGuilds(2);
        TestDataFactory.createHero(user.ContactId, guilds[0].Id, true);

        Superhero_Mission__c sm1 = TestDataFactory.createSuperHeroMission(false, guilds[0].Id, false);
        Superhero_Mission__c sm2 = TestDataFactory.createSuperHeroMission(true, guilds[1].Id, false);

        insert new List<Superhero_Mission__c> {sm1, sm2};
    }

    @isTest
    private static void getAllMissionsTest(){
        List<Superhero_Mission__c> missions = new List<Superhero_Mission__c>();
        User communityUser = [
            SELECT Id
            FROM User
            WHERE LastName = 'TestLast'
        ];

        TestDataFactory.assignPermissionSet(communityUser.Id, 'Hero_User');

        System.runAs(communityUser) {
            missions = AllMissionsCmpController.getAllMissions();
        }

        Assert.areEqual(2, missions.size(), 'Expected 2 missions');
    }
}